language: python

python:
  - "3.7"

env:
  - TOXENV=django111
  - TOXENV=django22
  - TOXENV=quality

sudo: required

cache: pip

before_install:
  - export BOTO_CONFIG=/dev/null
  - export DJANGO_SETTINGS_MODULE=VEDA.settings.test

install:
  - make requirements

script:
  - tox

after_success:
  - pip install -U codecov
  - codecov
