language: python

python:
  - "2.7"

sudo: required

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

# build tests
script:
    - make validate

after_success:
  - pip install -U codecov
  - codecov
