---
# ---
# Database information
# ---

# SANDBOX
#DATABASES:
#    default:
#        ENGINE: django.db.backends.sqlite3
#        NAME: sandbox.db

## PRODUCTION
DATABASES:
    default:
        ENGINE: 'django.db.backends.mysql'
        NAME:
        USER:
        PASSWORD:
        HOST:
        PORT: '3306'

django_secret_key: ""

# Django DEBUG global
# (set to false in prod)
debug: false

# ---
# AWS Buckets, Prefixes
# ---
# Studio/Platform
edx_s3_ingest_prefix:
edx_s3_ingest_bucket:
edx_s3_endpoint_bucket:

# CF
edx_cloudfront_prefix:

# Images
aws_video_images_bucket:
aws_video_images_prefix: "video-images/"


# VEDA Internal
veda_s3_upload_bucket:
veda_s3_hotstore_bucket:
veda_deliverable_bucket:
# Settings
multi_upload_barrier: 2000000000
veda_base_url:
s3_base_url: https://s3.amazonaws.com


# Transcripts
aws_video_transcripts_bucket:
aws_video_transcripts_prefix: video-transcripts/

# cielo24 api urls
cielo24_api_base_url: https://sandbox.cielo24.com/api

# 3playmedia api urls
three_play_api_base_url: https://api.3playmedia.com/
three_play_api_transcript_url: https://static.3playmedia.com/

# a token identifying a valid request from transcript provider
transcript_provider_request_token: test-token

# Ingest Secret
# TODO: Elminate access key after AWS Support ticket 08/20/17 regarding cross-account IAM role access.
veda_secret_access_key:
veda_access_key_id:

# ---
# email vars
# ---
veda_noreply_email:
admin_email:

# ---
# VEDA API
# ---
## VEDA API Auth
veda_api_url:
veda_auth_url:
veda_client_id:
veda_secret_key:
veda_token_url:

# ---
# VAL
# ---
val_api_url:
val_token_url:
val_video_images_url:
# Credentials
val_client_id:
val_secret_key:
val_password:
val_username:
val_transcript_create_url:
val_video_transcript_status_url:

# ---
# Celery Info
# ---
celery_app_name: veda_production
# can do multiple queues like so: foo,bar,baz
main_celery_queue: encode_worker
celery_receiver_queue: encode_worker
largefile_celery_queue: large_encode_worker
celery_stat_queue: transcode_stat
largefile_queue_barrier: 1000000000
celery_threads: 1

rabbitmq_broker:
rabbitmq_pass:
rabbitmq_user:

# ---
# Shotgun Variables (internal mediateam)
# ---
sg_server_path:
sg_script_name:
sg_script_key:

# ---
# Endpoints
# ---
threeplay_ftphost:
xuetang_api_url:
xuetang_api_shared_secret:

## Encoding Config
ffmpeg_compiled: "ffmpeg"
ffprobe_compiled: "ffprobe"
target_aspect_ratio: 1.7777778

# ----------
##---
# This is a list of encodes and their respective course
# boolean matches
encode_dict:
    review_proc:
        - review
    mobile_override:
        - override
    s3_proc:
        - mobile_high
        - mobile_low
        - audio_mp3
        - desktop_webm
        - desktop_mp4
        - hls

    yt_proc:
        - youtube

##---
# This is a list of encode profiles and their val profile matches
# boolean matches
val_profile_dict:
    mobile_low:
        - mobile_low

    desktop_mp4:
        - desktop_mp4

    override:
        - desktop_mp4
        - mobile_low
        - mobile_high

    mobile_high:
        - mobile_high

    audio_mp3:
        - audio_mp3

    desktop_webm:
        - desktop_webm

    youtube:
        - youtube
    review:
    hls:
        - hls

#--
# Heal settings
heal_start: 1
heal_end: 144

...
