---
# This configuration should only have static settings.

# Celery Info
onsite_worker: False
celery_threads: 1
celery_app_name: veda_production
celery_deliver_queue: deliver_worker
celery_heal_queue: heal_queue
celery_online_heal_queue: online_heal_queue

# S3 upload settings
multi_upload_barrier: 2000000000

# Encoding Config
ffmpeg_compiled: "ffmpeg"
ffprobe_compiled: "ffprobe"
target_aspect_ratio: 1.7777778

# This is a list of encodes and their respective course
# boolean matches
encode_dict:
    review_proc:
        - review
    mobile_override:
        - override
    s3_proc:
        - mobile_low
        - audio_mp3
        - desktop_mp4
        - hls

    yt_proc:
        - youtube

# This is a list of encode profiles and their val profile matches
# boolean matches
val_profile_dict:
    mobile_low:
        - mobile_low

    desktop_mp4:
        - desktop_mp4

    override:
        - desktop_mp4
        - mobile_low

    audio_mp3:
        - audio_mp3

    youtube:
        - youtube
    review:
    hls:
        - hls

global_timeout: 60
