version: "3"

services:
  redis:
    image: "redis"
    container_name: "veda.redis"
    tty: true
    networks: 
      - devstack_default

  pipeline:
    image: "ssemenova/veda-pipeline"
    container_name: "veda.pipeline"
    volumes:
      - ${VEDA_WORKSPACE}/edx-video-pipeline:/edx-video-pipeline
    tty: true
    networks: 
      - devstack_default

  http:
    image: "azarembok/veda-web-frontend"
    container_name: "veda-web-frontend"
    working_dir: "/edx-video-pipeline"
    command: bash -c 'source /edx/app/veda/veda_env && while true; do python manage.py runserver 0.0.0.0:8555 --settings=VEDA.settings.local; sleep 2; done'
    volumes:
       - ${VEDA_WORKSPACE}/edx-video-pipeline:/edx-video-pipeline
    ports:
       - "8000:8555"
    environment:
       redis_broker: "veda.redis"
    tty: true
    stdin_open: true
    networks: 
      - devstack_default

  encode:
    image: "ssemenova/veda-encode"
    container_name: "veda.encode"
    volumes:
      - ${VEDA_WORKSPACE}/edx-video-worker:/edx-video-worker
    tty: true
    networks: 
      - devstack_default

  deliver:
    image: "azarembok/veda-delivery-worker"
    container_name: "veda.deliver"
    volumes:
      - ${VEDA_WORKSPACE}/edx-video-pipeline:/edx-video-pipeline
    tty: true
    working_dir: "/edx-video-pipeline"
    # command: "python bin/deliver"
    environment:
      DJANGO_SETTINGS_MODULE: "VEDA.settings.local"
      redis_broker: "veda.redis"
      # PYTHONPATH: "/edx-video-pipeline"
      VIDEO_PIPELINE_CFG: "/edx-video-pipeline/instance_config.yaml"
    networks: 
      - devstack_default

networks:
    devstack_default:
      external: true
